package com.tsi2.streamrain.model;
// Generated 26/09/2017 05:05:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String email;
     private String nickname;
     private String password;
     private Boolean isBanned;
     private String country;
     private String city;
     private String facebookUserId;
     private String twitterUserId;
     private Set userChatMessgeses = new HashSet(0);
     private Set userChatMessgeses_1 = new HashSet(0);
     private Set userCommentses = new HashSet(0);
     private Set userUnfavses = new HashSet(0);
     private Set spoilerMarkses = new HashSet(0);
     private Set userFavses = new HashSet(0);
     private Set userViewses = new HashSet(0);
     private Set userRatingses = new HashSet(0);
     private Set userPpvses = new HashSet(0);
     private Set userSubscriptionses = new HashSet(0);

    public Users() {
    }

	
    public Users(String email, String nickname, String password, String country, String city) {
        this.email = email;
        this.nickname = nickname;
        this.password = password;
        this.country = country;
        this.city = city;
    }
    public Users(String email, String nickname, String password, Boolean isBanned, String country, String city, String facebookUserId, String twitterUserId, Set userChatMessgeses, Set userChatMessgeses_1, Set userCommentses, Set userUnfavses, Set spoilerMarkses, Set userFavses, Set userViewses, Set userRatingses, Set userPpvses, Set userSubscriptionses) {
       this.email = email;
       this.nickname = nickname;
       this.password = password;
       this.isBanned = isBanned;
       this.country = country;
       this.city = city;
       this.facebookUserId = facebookUserId;
       this.twitterUserId = twitterUserId;
       this.userChatMessgeses = userChatMessgeses;
       this.userChatMessgeses_1 = userChatMessgeses_1;
       this.userCommentses = userCommentses;
       this.userUnfavses = userUnfavses;
       this.spoilerMarkses = spoilerMarkses;
       this.userFavses = userFavses;
       this.userViewses = userViewses;
       this.userRatingses = userRatingses;
       this.userPpvses = userPpvses;
       this.userSubscriptionses = userSubscriptionses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Boolean getIsBanned() {
        return this.isBanned;
    }
    
    public void setIsBanned(Boolean isBanned) {
        this.isBanned = isBanned;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getFacebookUserId() {
        return this.facebookUserId;
    }
    
    public void setFacebookUserId(String facebookUserId) {
        this.facebookUserId = facebookUserId;
    }
    public String getTwitterUserId() {
        return this.twitterUserId;
    }
    
    public void setTwitterUserId(String twitterUserId) {
        this.twitterUserId = twitterUserId;
    }
    public Set getUserChatMessgeses() {
        return this.userChatMessgeses;
    }
    
    public void setUserChatMessgeses(Set userChatMessgeses) {
        this.userChatMessgeses = userChatMessgeses;
    }
    public Set getUserChatMessgeses_1() {
        return this.userChatMessgeses_1;
    }
    
    public void setUserChatMessgeses_1(Set userChatMessgeses_1) {
        this.userChatMessgeses_1 = userChatMessgeses_1;
    }
    public Set getUserCommentses() {
        return this.userCommentses;
    }
    
    public void setUserCommentses(Set userCommentses) {
        this.userCommentses = userCommentses;
    }
    public Set getUserUnfavses() {
        return this.userUnfavses;
    }
    
    public void setUserUnfavses(Set userUnfavses) {
        this.userUnfavses = userUnfavses;
    }
    public Set getSpoilerMarkses() {
        return this.spoilerMarkses;
    }
    
    public void setSpoilerMarkses(Set spoilerMarkses) {
        this.spoilerMarkses = spoilerMarkses;
    }
    public Set getUserFavses() {
        return this.userFavses;
    }
    
    public void setUserFavses(Set userFavses) {
        this.userFavses = userFavses;
    }
    public Set getUserViewses() {
        return this.userViewses;
    }
    
    public void setUserViewses(Set userViewses) {
        this.userViewses = userViewses;
    }
    public Set getUserRatingses() {
        return this.userRatingses;
    }
    
    public void setUserRatingses(Set userRatingses) {
        this.userRatingses = userRatingses;
    }
    public Set getUserPpvses() {
        return this.userPpvses;
    }
    
    public void setUserPpvses(Set userPpvses) {
        this.userPpvses = userPpvses;
    }
    public Set getUserSubscriptionses() {
        return this.userSubscriptionses;
    }
    
    public void setUserSubscriptionses(Set userSubscriptionses) {
        this.userSubscriptionses = userSubscriptionses;
    }




}


